environment = "development"
env         = "development"
#subscription_id   = "4ac7e4ba-2b33-4c38-8852-1a6ba4098aa3"
resource_group_hp = "patelh-sandbox-rg"
#tenant_id         = "3e0088dc-0629-4ae6-aa8c-813e7a296f50"
#sa_access_key     = "X/oxLevITii1fcgdxp1oRq+0ujmHELv0dFcOR9k2Pfe8qPEBn8fAm/JQvYpeEIOmEpiTlAdpw4dx+AStoZSU+w=="
tenant_id     = data.azurerm_key_vault_secret.tenant_id.value
sa_access_key = data.azurerm_key_vault_secret.sa_access_key.value
object_id     = data.azurerm_key_vault_secret.object_id.value
