# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'UKDDC_Azure_Subscription'
    backendAzureRmResourceGroupName: 'patelh-sandbox-rg'
    backendAzureRmStorageAccountName: 'sahpstatevuks01'
    backendAzureRmContainerName: 'tfstatefiles'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'UKDDC_Azure_Subscription'
    backendAzureRmResourceGroupName: 'patelh-sandbox-rg'

# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     environmentServiceNameAzureRM: 'UKDDC_Azure_Subscription'
#     backendAzureRmResourceGroupName: 'patelh-sandbox-rg'