# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


jobs:
  - job:
    displayName: Terraform init-plan-apply
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.15.0'

    - script: |
        terraform init
      displayName: 'Terraform Init'

    - script: |
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -input=false tfplan
      displayName: 'Terraform Apply'
