# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
- name: environments
  type: object
  default:
    - name: hpdev
      dependsOnEnv: ""
    - name: hpprod
      dependsOnEnv: "hpdev"

variables:
  tfversion: '1.7.1'
  backendServiceArm: 'UKDDC_Azure_Subscription'
  backendAzureRmResourceGroupName: 'patelh-sandbox-rg'
  backendAzureRmStorageAccountName: 'sahpstatevuks01'
  backendAzureRmContainerName: 'tfstatefiles'
  backendAzureRmKey: 'terraform.tfstate'
  environmentServiceNameAzureRM: 'UKDDC_Azure_Subscription'
 
stages:
- ${{ each env in parameters.environments }}:
  - stage: Terraform_${{ env.name }}
    displayName: Terraform for ${{ env.name }}
    condition: and(succeeded(), or(eq('${{ env.dependsOnEnv }}', ''), succeeded('Terraform_${{ env.dependsOnEnv }}')))
    jobs:
      - deployment: terraformDeploy_${{ env.name }}
        displayName: Terraform Deploy for ${{ env.name }}
        environment: ${{ env.name }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformTaskV4@4
                  displayName: terraform init for ${{ env.name }}
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    backendServiceArm: ${{ variables.backendServiceArm }}
                    backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
                    backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
                    backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
                    backendAzureRmKey: ${{ variables.backendAzureRmKey }}

                - template: template/terraform.plan-apply.yaml
                  parameters:
                    environmentServiceNameAzureRM: ${{ variables.environmentServiceNameAzureRM }}
                    backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
