version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: webappadministrator
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: sqldb-webapp-dev
    volumes:
      - ./wordpress:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sqldb-webapp-dev
      MYSQL_USER: webappadministrator
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
