trigger:
- main

pr:
- none

parameters:
- name: environments
  type: object
  default:
    - name: development

pool:
  vmImage: ubuntu-latest

variables:
  backendServiceArm: 'UKDDC_Azure_Subscription'


stages:
  - stage: Terraform_Run_Checks
    jobs:
      - job: Dev_Checks
        steps:
        - task: AzureCLI@2
          displayName: Run checks
          inputs:
            azureSubscription: "${{ variables.backendServiceArm }}"
            scriptType: "bash"
            scriptLocation: "inlineScript"
            inlineScript: |
              # export TF_LOG="TRACE"
              az account show
              terraform apply -auto-approve
              workingDirectory: "$(System.DefaultWorkingDirectory)/checks" 
              commandOptions: "-var-file=../config/checks.tfvars -lock=false"   