trigger:
- codefix*
- feature*

pool:
  vmImage: 'ubuntu-latest'

variables:
  backendServiceArm: 'UKDDC_Azure_Subscription'

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  inputs:
    terraformVersion: '1.8.4'

- task: TerraformCLI@1
  inputs:
    command: 'init'
    workingDirectory: 'checks'
    backendType: 'local'

- task: TerraformCLI@1
  displayName: 'Terraform format'
  inputs:
    command: 'fmt'
    workingDirectory: 'checks'
    allowTelemetryCollection: false

- task: TerraformCLI@1
  displayName: 'Terraform Validate'
  inputs:
    command: 'validate'
    workingDirectory: 'checks'
    allowTelemetryCollection: false

- task: AzureCLI@2  
  displayName: 'Export Azure Subscription ID'  
  inputs:    
    azureSubscription: UKDDC_Azure_Subscription    
    scriptType: bash    
    addSpnToEnvironment: true    
    scriptLocation: inlineScript    
    inlineScript: |      
      # Extract the service principal details and set them as pipeline variables      
      SubId=$(az account show --query id --output tsv)      
      echo "##vso[task.setvariable variable=TF_VAR_az-subscription-id]$SubId"

- task: TerraformCLI@1
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/checks'
    environmentServiceName: ${{ variables.backendServiceArm }}
    runAzLogin: true
    commandOptions: '-var-file=../config/checks.tfvars -lock=false'
    allowTelemetryCollection: true
    failOnStandardError: true
