trigger:

- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  inputs:
    terraformVersion: '1.8.4'

- task: TerraformCLI@1
  inputs:
    command: 'init'
    workingDirectory: 'checks'
    backendType: 'local'

- task: TerraformCLI@1
  displayName: 'Terraform format'
  inputs:
    command: 'fmt'
    workingDirectory: 'checks'
    allowTelemetryCollection: false

- task: TerraformCLI@1
  displayName: 'Terraform Validate'
  inputs:
    command: 'validate'
    workingDirectory: 'checks'
    allowTelemetryCollection: false

- task: TerraformCLI@1
  displayName: 'Terraform Apply'
  inputs:
    azureSubscription: UKDDC_Azure_Subscription
    command: 'apply'
    workingDirectory: 'checks'
    commandOptions: "-var-file=../config/checks.tfvars -lock=false"
    allowTelemetryCollection: false